name: Docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install
        working-directory: ./docs

      - name: Build docs
        run: yarn run build
        working-directory: ./docs

      - name: Push docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist

      